# Generated by Django 4.2.10 on 2024-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=16, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('domain_ssh', models.CharField(blank=True, max_length=225, null=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_vlan', models.IntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=16, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('domain_ssh', models.CharField(blank=True, max_length=225, null=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('vtp_role', models.CharField(blank=True, max_length=12, null=True)),
                ('vtp_domain_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
