# Generated by Django 4.2.10 on 2024-03-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksite',
            name='administrator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='networksite',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_api.networksite'),
        ),
        migrations.AddField(
            model_name='switch',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_api.networksite'),
        ),
    ]
