# Generated by Django 4.2.10 on 2024-03-08 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network_api', '0002_networksite_administrator_networksite_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksite',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
