# Generated by Django 4.2.10 on 2024-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0003_alter_networksite_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksite',
            name='devices',
            field=models.IntegerField(default=0),
        ),
    ]
