# Generated by Django 4.2.10 on 2024-03-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0004_networksite_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networksite',
            name='devices',
        ),
    ]
